import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dist=path.join(root,'dist'),htmlFiles=await walk(dist,'.html'),publicPaths=new Set((await walk(dist)).map(file=>`/${path.relative(dist,file).replaceAll('\\','/')}`)),failures=[];
for(const file of htmlFiles){const html=await readFile(file,'utf8'),rel=path.relative(dist,file);if((html.match(/<h1\b/g)||[]).length!==1)failures.push(`${rel}: debe contener un H1`);for(const required of['<title>','name="description"','rel="canonical"','application/ld+json'])if(!html.includes(required))failures.push(`${rel}: falta ${required}`);for(const match of html.matchAll(/(?:href|src)="(\/estante-medido\/[^"#?]*)/g)){let target=match[1].replace('/estante-medido','')||'/index.html';if(target.endsWith('/'))target+='index.html';if(!publicPaths.has(target))failures.push(`${rel}: referencia local ausente ${match[1]}`);}for(const script of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))try{JSON.parse(script[1]);}catch{failures.push(`${rel}: JSON-LD no válido`);}validateInlineScripts(html,rel,failures);}
const sitemap=await readFile(path.join(dist,'sitemap.xml'),'utf8');for(const required of['repartir-baldas/','cuantas-baldas/','lista-corte-estanteria/'])if(!sitemap.includes(required))failures.push(`sitemap: falta ${required}`);if(sitemap.includes('404'))failures.push('sitemap: contiene 404');
for(const asset of ['/assets/commerce.css','/assets/commerce-entry.css','/assets/board-commerce.js','/assets/products/board-products.js','/assets/math/cut-optimizer.js'])if(!publicPaths.has(asset))failures.push(`build: falta ${asset}`);
const home=await readFile(path.join(dist,'index.html'),'utf8');if(!home.includes('Comparador de tableros reales'))failures.push('inicio: falta la entrada estática al comparador');
const cut=await readFile(path.join(dist,'lista-corte-estanteria','index.html'),'utf8');for(const required of['Compara tableros que puedan contener tus piezas','data-board-commerce-status','commerce-entry.css'])if(!cut.includes(required))failures.push(`lista de corte: falta ${required}`);
const methodology=await readFile(path.join(dist,'metodologia','index.html'),'utf8');for(const required of['55 %','45 %','0 %','Comisión'])if(!methodology.includes(required))failures.push(`metodología comercial: falta ${required}`);
if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}else console.log(`Checked ${htmlFiles.length} HTML files, commerce assets/output, inline JavaScript, local references, JSON-LD and sitemap.`);
function validateInlineScripts(html,rel,failures){for(const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){const attrs=match[1]||'';if(/\bsrc\s*=/i.test(attrs))continue;const type=(attrs.match(/\btype=["']([^"']+)["']/i)?.[1]||'').toLowerCase();if(type&&!['text/javascript','application/javascript'].includes(type))continue;try{new Function(match[2]);}catch(error){failures.push(`${rel}: JavaScript inline no válido (${error.message})`);}}}
async function walk(directory,extension=null){const files=[];for(const name of await readdir(directory)){const full=path.join(directory,name);if((await stat(full)).isDirectory())files.push(...await walk(full,extension));else if(!extension||full.endsWith(extension))files.push(full);}return files;}
